# Generated by Django 3.2.16 on 2023-06-23 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_auto_20230616_1626"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "default_related_name": "posts",
                "ordering": ("-pub_date",),
                "verbose_name": "публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
    ]
