# Generated by Django 3.2.16 on 2023-07-26 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0017_alter_post_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "публикация", "verbose_name_plural": "Публикации"},
        ),
    ]
