# Generated by Django 3.2.16 on 2023-08-03 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0018_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={
                "default_related_name": "comments",
                "ordering": ("created_at",),
                "verbose_name": "комментарий",
                "verbose_name_plural": "Комментарии",
            },
        ),
    ]
